### PR TITLE
Elgg 1.8 - Profile Manager v 7.6.1 italian language

### PR DESCRIPTION
**Pull request by michelesbw**
<?php

// italian translation by Michele @ https://socialbusinessworld.org, the Social Network for a Sustainable World
// of Profile Manager V 7.6.1 (community.elgg.org/plugins/385114/releases/7.6.1) by ColdTrick for Elgg 1.8

$language = array (
  'item:object:custom_profile_field' => 'Custom Profile Field',
  'item:object:custom_profile_field_category' => 'Custom Profile Field Category',
  'item:object:custom_profile_type' => 'Custom Profile Type',
  'item:object:custom_group_field' => 'Custom Group Field',
  'profile:custom_profile_type' => 'Custom Profile Type',
  'admin:appearance:group_fields' => 'Edit Group Fields',
  'admin:appearance:export_fields' => 'Export Profile Data',
  'admin:appearance:user_summary_control' => 'User Summary Control',
  'admin:groups' => 'Groups',
  'admin:groups:export' => 'Export groups',
  'admin:users:export' => 'Export users',
  'admin:users:inactive' => 'List inactive users',
  'profile_manager:settings:registration' => 'Registration',
  'profile_manager:settings:edit_profile' => 'Modifica profilo',
  'profile_manager:settings:view_profile' => 'Visualizza profilo',
  'profile_manager:settings:group' => 'Modifica profilo del gruppo',
  'profile_manager:settings:other' => 'Altro',
  'profile_manager:settings:profile_icon_on_register' => 'Add mandatory profile icon input field on register form',
  'profile_manager:settings:show_account_hints' => 'Show hints for default account registration questions',
  'profile_manager:settings:simple_access_control' => 'Show just one access control dropdown on edit profile form',
  'profile_manager:settings:default_profile_type' => 'Default profile type on registration form',
  'profile_manager:settings:hide_profile_type_default' => 'Hide the \'Default\' profile type on registration form',
  'profile_manager:settings:hide_non_editables' => 'Hide the non editable fields from the Edit Profile form',
  'profile_manager:settings:edit_profile_mode' => 'How to show the \'edit profile\' screen',
  'profile_manager:settings:edit_profile_mode:list' => 'List',
  'profile_manager:settings:edit_profile_mode:tabbed' => 'Tabbed',
  'profile_manager:settings:show_profile_type_on_profile' => 'Show the users profile type on the profile',
  'profile_manager:settings:display_categories' => 'Select how the different categories are displayed on the profile',
  'profile_manager:settings:display_categories:option:plain' => 'Plain',
  'profile_manager:settings:display_categories:option:accordion' => 'Accordion',
  'profile_manager:settings:display_system_category' => 'Show an extra category on the profile with systemdata (only for admins)',
  'profile_manager:settings:profile_type_selection' => 'Who can change the profile type?',
  'profile_manager:settings:profile_type_selection:option:user' => 'User',
  'profile_manager:settings:profile_type_selection:option:admin' => 'Admin only',
  'profile_manager:settings:description_position' => 'Where to position the description ("About me") field',
  'profile_manager:settings:user_summary_control' => 'Let Profile Manager control the user summary / listing view',
  'profile_manager:settings:enable_profile_completeness_widget' => 'Enable the profile completeness widget',
  'profile_manager:settings:enable_username_change' => 'Allow users to change their username in settings',
  'profile_manager:settings:enable_username_change:option:admin' => 'Admin only',
  'profile_manager:settings:enable_site_join_river_event' => 'Add a river event when people join this site',
  'profile_manager:settings:registration:terms' => 'To show an \'Accept terms\' field on the registration page, please fill in the URL to the terms below',
  'profile_manager:settings:registration:extra_fields' => 'Where to show extra profile fields',
  'profile_manager:settings:registration:extra_fields:extend' => 'Below default registration form',
  'profile_manager:settings:registration:extra_fields:beside' => 'Beside registration form',
  'profile_manager:settings:registration:free_text' => 'Enter extra text to show on the registration page',
  'profile_manager:settings:group:group_limit_name' => 'Maximum number of times a group name can be edited',
  'profile_manager:settings:group:group_limit_description' => 'Maximum number of times a group description can be edited',
  'profile_manager:settings:group:limit:unlimited' => 'Unlimited',
  'profile_manager:settings:group:limit:never' => 'Never',
  'profile_manager:settings:group:limit:info' => 'These limits do not apply to site administrators',
  'profile_manager:admin:metadata_name' => 'Name',
  'profile_manager:admin:metadata_label' => 'Label',
  'profile_manager:admin:metadata_hint' => 'Hint',
  'profile_manager:admin:metadata_description' => 'Description',
  'profile_manager:admin:metadata_label_translated' => 'Label (Translated)',
  'profile_manager:admin:metadata_label_untranslated' => 'Label (Untranslated)',
  'profile_manager:admin:metadata_options' => 'Opzioni (separate da virgola)',
  'profile_manager:admin:field_type' => 'Field Type',
  'profile_manager:admin:options:datepicker' => 'Datepicker',
  'profile_manager:admin:options:pm_datepicker' => 'Datepicker (Profile Manager Style)',
  'profile_manager:admin:options:dropdown' => 'Dropdown',
  'profile_manager:admin:options:radio' => 'Radio',
  'profile_manager:admin:options:multiselect' => 'MultiSelect',
  'profile_manager:admin:options:file' => 'File',
  'profile_manager:admin:options:pm_rating' => 'Rating',
  'profile_manager:admin:additional_options' => 'Additional options',
  'profile_manager:admin:show_on_register' => 'Show on register form',
  'profile_manager:admin:mandatory' => 'Obbligatorio',
  'profile_manager:admin:user_editable' => 'User can edit this field',
  'profile_manager:admin:output_as_tags' => 'Show on profile as tags',
  'profile_manager:admin:admin_only' => 'Admin only field',
  'profile_manager:admin:count_for_completeness' => 'Count this field in profile completeness widget',
  'profile_manager:admin:blank_available' => 'Field has a blank option',
  'profile_manager:admin:option_unavailable' => 'Opzione non disponibile',
  'profile_manager:admin:show_on_register:description' => 'If you want this field to be on the register form.',
  'profile_manager:admin:mandatory:description' => 'If you want this field to be mandatory (only applies to the register form).',
  'profile_manager:admin:user_editable:description' => 'If set to \'No\' users can\'t edit this field (handy when data is managed in an external system).',
  'profile_manager:admin:output_as_tags:description' => 'Data output will be handle as tags (only applies on user profile).',
  'profile_manager:admin:admin_only:description' => 'Select \'Yes\' if field is only available for admins.',
  'profile_manager:admin:blank_available:description' => 'Select \'Yes\' if a blank option should be added to the field options',
  'profile_manager:profile_fields:list:title' => 'Campi del profilo',
  'profile_manager:profile_fields:no_fields' => 'Currently no fields are configured using the Profile Manager plugin. Add your own or import with one of the actions below.',
  'profile_manager:profile_fields:add' => 'Add a new profile field',
  'profile_manager:profile_fields:edit' => 'Edit a profile field',
  'profile_manager:profile_fields:add:description' => 'Here you can edit the fields a user can edit on his/her profile',
  'profile_manager:group_fields:list:title' => 'Campi del profilo dei gruppi',
  'profile_manager:group_fields:add:description' => 'Here you can edit the fields that show on a group profile page',
  'profile_manager:group_fields:add' => 'Add a new group profile field',
  'profile_manager:group_fields:edit' => 'Edit a group profile field',
  'profile_manager:categories:add' => 'Add a new category',
  'profile_manager:categories:edit' => 'Edit a category',
  'profile_manager:categories:list:title' => 'Categorie',
  'profile_manager:categories:list:default' => 'Default',
  'profile_manager:categories:list:system' => 'System (admin only)',
  'profile_manager:categories:list:view_all' => 'View all fields',
  'profile_manager:categories:list:no_categories' => 'No categories defined',
  'profile_manager:categories:delete:confirm' => 'Are you sure you wish to delete this category?',
  'profile_manager:profile_types:add' => 'Add a new profile type',
  'profile_manager:profile_types:edit' => 'Edit a profile type',
  'profile_manager:profile_types:list:title' => 'Profile Types',
  'profile_manager:profile_types:list:no_types' => 'No profile types defined',
  'profile_manager:profile_types:delete:confirm' => 'Are you sure you wish to delete this profile type?',
  'profile_manager:user_details:profile_type' => 'Profile Type',
  'profile_manager:user_summary_control:config' => 'Configuration',
  'profile_manager:user_summary_control:info' => 'Add fields to the different containers and see in the preview the result of the configuration. If you are satisfied you can \'Save\' the configuration.',
  'profile_manager:user_summary_control:container:title' => 'Title',
  'profile_manager:user_summary_control:container:entity_menu' => 'Entity Menu',
  'profile_manager:user_summary_control:container:subtitle' => 'Subtitle',
  'profile_manager:user_summary_control:container:content' => 'Content',
  'profile_manager:user_summary_control:options:spacers' => 'Spacers',
  'profile_manager:user_summary_control:options:spacers:new_line' => 'New line',
  'profile_manager:user_summary_control:options:spacers:space' => 'Space',
  'profile_manager:user_summary_control:options:spacers:dash' => '-',
  'profile_manager:admin:users:inactive:last_login' => 'Last login before',
  'profile_manager:admin:users:inactive:list' => 'Inactive users',
  'profile_manager:admin:users:inactive:never' => 'Never',
  'profile_manager:admin:users:inactive:download' => 'Download',
  'profile_manager:actions:title' => 'Actions',
  'profile_manager:actions:reset:description' => 'Removes all custom profile fields',
  'profile_manager:actions:reset:confirm' => 'Are you sure you wish to reset all profile fields?',
  'profile_manager:actions:reset:error:unknown' => 'Unknown error occurred while resetting all profile fields',
  'profile_manager:actions:reset:error:wrong_type' => 'Wrong profile field type (group or profile)',
  'profile_manager:actions:reset:success' => 'Reset succesful',
  'profile_manager:actions:import:from_custom' => 'Import custom fields',
  'profile_manager:actions:import:from_custom:description' => 'Imports previous defined (with default Elgg functionality) profile fields',
  'profile_manager:actions:import:from_custom:confirm' => 'Are you sure you wish to import custom fields?',
  'profile_manager:actions:import:from_custom:no_fields' => 'No custom fields available for import',
  'profile_manager:actions:import:from_custom:new_fields' => 'Succesfully imported <b>%s</b> new fields',
  'profile_manager:actions:import:from_default' => 'Import default fields',
  'profile_manager:actions:import:from_default:description' => 'Imports Elgg\'s default fields',
  'profile_manager:actions:import:from_default:confirm' => 'Are you sure you wish to import default fields?',
  'profile_manager:actions:import:from_default:no_fields' => 'No default fields available for import',
  'profile_manager:actions:import:from_default:new_fields' => 'Succesfully imported <b>%s</b> new fields',
  'profile_manager:actions:import:from_default:error:wrong_type' => 'Wrong profile field type (group or profile)',
  'profile_manager:actions:export' => 'Export',
  'profile_manager:actions:export:description' => 'Export profile data to a csv file',
  'profile_manager:export:title' => 'Export Profile Data',
  'profile_manager:export:description:custom_profile_field' => 'This function will export all <b>user</b> metadata based on selected fields.',
  'profile_manager:export:description:custom_group_field' => 'This function will export all <b>group</b> metadata based on selected fields.',
  'profile_manager:export:list:title' => 'Select the fields which you want to be exported',
  'profile_manager:export:list:include_group_membership' => 'Include group membership',
  'profile_manager:export:nofields' => 'No custom profile fields available for export',
  'profile_manager:group:edit:limit' => 'You can edit this field %s more time(s)',
  'profile_manager:actions:configuration:backup' => 'Backup',
  'profile_manager:actions:configuration:backup:description' => 'Backup the configuration of these fields (categories and types are not backed up)',
  'profile_manager:actions:configuration:restore' => 'Restore',
  'profile_manager:actions:configuration:restore:description' => 'Restore a previously backed up configuration file (<b>you will loose relations between fields and categories</b>)',
  'profile_manager:actions:configuration:restore:upload' => 'Restore',
  'profile_manager:actions:restore:success' => 'Restore successful',
  'profile_manager:actions:restore:error:deleting' => 'Error while restoring: couldn\'t delete current fields',
  'profile_manager:actions:restore:error:fieldtype' => 'Error while restoring: fieldtypes do not match',
  'profile_manager:actions:restore:error:corrupt' => 'Error while restoring: backup file seems to be corrupt or information is missing',
  'profile_manager:actions:restore:error:json' => 'Error while restoring: invalid json file',
  'profile_manager:actions:restore:error:nofile' => 'Error while restoring: no file uploaded',
  'profile_manager:actions:new:success' => 'Succesfully added new custom profile field',
  'profile_manager:actions:new:error:metadata_name_missing' => 'No metadata name provided',
  'profile_manager:actions:new:error:metadata_name_invalid' => 'Metadata name is an invalid name',
  'profile_manager:actions:new:error:metadata_options' => 'You need to enter options when using this type',
  'profile_manager:actions:new:error:unknown' => 'Unknown error occurred when saving a new custom profile field',
  'profile_manager:action:new:error:type' => 'Wrong profile field type (group or profile)',
  'profile_manager:actions:edit:error:unknown' => 'Error fetching profile field data',
  'profile_manager:actions:delete:confirm' => 'Are you sure you wish to delete this field?',
  'profile_manager:actions:delete:error:unknown' => 'Unknown error occurred while deleting',
  'profile_manager:actions:toggle_option:error:unknown' => 'Unknown error occurred while changing the option',
  'profile_manager:actions:change_category:error:unknown' => 'An unknown error occured while changing the category',
  'profile_manager:action:category:add:error:name' => 'No name or an invalid name provided for the category',
  'profile_manager:action:category:add:error:object' => 'Error while creating the category object',
  'profile_manager:action:category:add:error:save' => 'Error while saving the category object',
  'profile_manager:action:category:add:succes' => 'The category was created succesfully',
  'profile_manager:action:category:delete:error:guid' => 'No GUID provided',
  'profile_manager:action:category:delete:error:type' => 'The provided GUID is not a custom profile field category',
  'profile_manager:action:category:delete:error:delete' => 'An error occured while deleting the category',
  'profile_manager:action:category:delete:succes' => 'The category was deleted succesfully',
  'profile_manager:action:profile_types:add:error:name' => 'No name or an invalid name provided for the Custom Profile Type',
  'profile_manager:action:profile_types:add:error:object' => 'Error while creating the Custom Profile Type',
  'profile_manager:action:profile_types:add:error:save' => 'Error while saving the Custom Profile Type',
  'profile_manager:action:profile_types:add:succes' => 'The Custom profile Type was created succesfully',
  'profile_manager:action:profile_types:delete:error:guid' => 'No GUID provided',
  'profile_manager:action:profile_types:delete:error:type' => 'The provided GUID is not an Custom Profile Type',
  'profile_manager:action:profile_types:delete:error:delete' => 'An unknown error occured while deleting the Custom Profile Type',
  'profile_manager:action:profile_types:delete:succes' => 'The Custom Profile Type was deleted succesfully',
  'profile_manager:action:username:change:succes' => 'Username cambiato con successo',
  'profile_manager:tooltips:profile_field' => '<b>Profile Field</b><br>

			Here you can add a new profile field.<br><br>

			If you leave the label empty, you can internationalize the profile field label (<i>profile:[name]</i>).<br><br>

			Use the hint field to supply on input forms (register and profile/group edit) a hoverable icon with a field description.

			If you leave the hint empty, you can internationalize the hint (<i>profile:hint:[name]</i>).<br><br>

			Options are only mandatory for fieldtypes <i>Dropdown, Radio and MultiSelect</i>.',
  'profile_manager:tooltips:profile_field_additional' => '<b>Show on register</b><br>

			If you want this field to be on the register form.<br><br>

			

			<b>Mandatory</b><br>

			If you want this field to be mandatory (only applies to the register form).<br><br>

			

			<b>User editable</b><br>

			If set to \'No\' users can\'t edit this field (handy when data is managed in an external system).<br><br>

			

			<b>Show as tags</b><br>

			Data output will be handle as tags (only applies on user profile).<br><br>

			

			<b>Admin only field</b><br>

			Select \'Yes\' if field is only available for admins.',
  'profile_manager:tooltips:category' => '<b>Category</b><br>

			Here you can add a new profile category.<br><br>

			If you leave the label empty, you can internationalize the category label (<i>profile:categories:[name]</i>).<br><br>

			

			If Profile Types are defined you can choose on which profile type this category applies. If no profile is specified, the category applies to all profile types (even undefined).',
  'profile_manager:tooltips:category_list' => '<b>Categories</b><br>

			Shows a list of all configured categories.<br><br>

			

			<i>Default</i> is the category that applies to all profiles.<br><br>

			

			Add fields to these categories by dropping them on the categories.<br><br>

			

			Click the category label to filter the visible fields. Clicking view all fields shows all fields.<br><br>

			

			You can also change the order of the categories by dragging them (<i>Default can\'t be dragged</i>. <br><br>

			

			Click the edit icon to edit the category.',
  'profile_manager:tooltips:profile_type' => '<b>Profile Type</b><br>

			Here you can add a new profile type.<br><br>

			If you leave the label empty, you can internationalize the profile type label (<i>profile:types:[name]</i>).<br><br>

			Enter a description which users can see when selecting this profile type or leave it empty to internationalize (<i>profile:types:[name]:description</i>).<br><br>

			

			If Categories are defined you can choose which categories apply to this profile type.',
  'profile_manager:tooltips:profile_type_list' => '<b>Profile Types</b><br>

			Shows a list of all configured profile types.<br><br>

			Click the edit icon to edit the profile type.',
  'profile_manager:tooltips:actions' => '<b>Actions</b><br>

			Various actions related to these profile fields.',
  'widgets:profile_completeness:title' => 'Completamento profilo',
  'widgets:profile_completeness:description' => 'Mostra completamento profilo',
  'widgets:profile_completeness:view:tips' => 'Suggerimento! Aggiorna il tuo %s per migliorarne la completezza.',
  'widgets:profile_completeness:view:complete' => 'Congratulazioni! Profilo completo al 100% !',
  'widgets:register:title' => 'Registrati',
  'widgets:register:description' => 'Show a register box',
  'widgets:register:loggedout' => 'Devi aver effettuato l\'accesso per usare questo gadget',
  'profile_manager:datepicker:trigger' => 'Seleziona una data',
  'profile_manager:datepicker:output:dateformat' => '%a %d %b %Y',
  'profile_manager:datepicker:input:dateformat' => '%m/%d/%Y',
  'profile_manager:datepicker:input:dateformat_js' => 'gg/mm/anno',
  'profile_manager:input:multi_select:empty_text' => 'Per favore seleziona...',
  'profile_manager:profile:edit:custom_profile_type:label' => 'Seleziona il tuo tipo di profilo',
  'profile_manager:profile:edit:custom_profile_type:description' => 'Descrizione del tipo di profilo selezionato',
  'profile_manager:profile:edit:custom_profile_type:default' => 'Default',
  'profile_manager:non_editable:info' => 'Questo campo non può essere modificato',
  'profile_manager:register:mandatory' => 'I campi evidenziati con un * sono obbligatori',
  'profile_manager:register:hints:name' => 'Inserisci il nome che sarà mostrato nel tuo profilo',
  'profile_manager:register:hints:username' => 'Puoi usare il tuo nome utente per entrare',
  'profile_manager:register:hints:email' => 'Questo indirizzo email sarà usato per inviarti i messaggi di sistema e non sarà visibile agli altri utenti',
  'profile_manager:register:hints:password' => 'Password necessaria per entrare',
  'profile_manager:register:hints:passwordagain' => 'Reinserisci la password per conferma',
  'profile_manager:register:profile_icon' => 'E\' necessario che tu inserisca un\'immagine per il tuo profilo',
  'profile_manager:registration:accept_terms' => 'Ho letto ed accettato i %sTermini e condizioni%s',
  'profile_manager:simple_access_control' => 'Scegli chi può vedere le informazioni del tuo profilo',
  'profile_manager:register_pre_check:missing' => 'Il campo seguente deve essere compilato: %s',
  'profile_manager:register_pre_check:terms' => 'Devi accettare i termini per completare la registrazione',
  'profile_manager:register_pre_check:profile_icon:error' => 'Errore durante il caricamento della tua immagine del profilo',
  'profile_manager:register_pre_check:profile_icon:nosupportedimage' => 'L\'immagine caricata non è del formato giusto (jpg, gif, png)',
  'profile_manager:admin:adduser:notify' => 'Notifica utente',
  'profile_manager:admin:adduser:use_default_access' => 'Extra metadata created based on site default access level',
  'profile_manager:admin:adduser:extra_metadata' => 'Aggiungi dati profilo extra',
  'profile_manager:account:username:button' => 'Clicca per cambiare il tuo nome utente',
  'profile_manager:account:username:info' => 'Cambia il tuo nome utente. Un\'icona ti dirà se il nome utente inserito è valido e disponibile.',
  'river:join:site:default' => '%s si è iscritto/a al sito',
  'profile_manager:account:login_history' => 'Storico login',
  'profile_manager:account:login_history:date' => 'Data',
  'profile_manager:account:login_history:ip' => 'Indirizzo IP',
);
add_translation("it", $language);

### CODE REVIEW

**Comment by jdalsem** [comment]
i think you did something wrong, because this Pull Request is messed up. You should fork the plugin and add a new file for the new language

**Comment by michelesbw** [comment]
Sorry Jeroen...first time here on Github trying to commit something...
Now it should be ok, please check the new commit and I also put the file on the community at https://community.elgg.org/plugins/1981210
Cheers

**Comment by jdalsem** [comment]
there is no change on this PR as far as i can see

**Comment by michelesbw** [comment]
mmmm I do see the it.php new file under my forked profile_manager/1.8/languages/ ... thought being a fork of your version you received some notification...how do I "ask" you to condier it for your repository?

**Comment by jdalsem** [comment]
you need to create a new PR of your fork against the branch of the Profile Manager (select the correct branch) like here: https://github.com/michelesbw/profile_manager/compare/elgg_1.8?expand=1 it should preview with only 1 commit (your it.php)

**Comment by michelesbw** [comment]
Mmmm I'm also going through Help here but realy not user-friendly at all....at least at the beginning...hope works now but will go on with Elgg community as here I feel completely out of water :)

**Comment by jdalsem** [comment]
it worked fine... just read up on github and try it a few times, you will get the hang of it at some point. Then you will have a new ability to contribute to open source projects even more!

**Comment by michelesbw** [comment]
Nice...will try again, let's see :)
Cheers

**Pull request closed without merging**
