### PR TITLE
WIP feat(api): make it easier to use profile manager for other custom field types

### PR DESCRIPTION
**Pull request by hypeJunction**
Implements a number of UI changes and adds some API to make it easier to
leverage profile managers admin interface to manage fields for other
entity types and subtypes

form

### CODE REVIEW

**Comment by hypeJunction** [comment]
There will be more coming as I work my way through it.

**Comment by jdalsem** [comment]
Bring it on :) It is probably very fun to look at all the ancient code :)

**Comment by hypeJunction** [comment]
I hate it :)

**Comment by hypeJunction** [comment]
Omg, you owe me a day of life I am never getting back.

**Comment by hypeJunction** [comment]
I am giving up. I wasted a day and it's a tip of the iceberg. I am just going to hack my way through to finish the project. I don't want to see profile manager ever again.

**Comment by jdalsem** [comment]
it is not so bad... the problem is, it is a lot of code... and if you want to do it right for 2.3... then you need to update a lot.

**Comment by hypeJunction** [comment]
The problem is not the API usage but endless loops of code. If I want to change one small thing in a single profile field, I need to replace and entire profile or form view. Honestly, I had enough. I just refuse to touch any more profile manager projects.

**Comment by jdalsem** [comment]
Are you finished with these changes?

**Comment by hypeJunction** [comment]
I am not gonna be adding anything else, if that's what you are asking. I have implemented some of these in a custom plugin and shipped off the project, so I won't be coming back to it

**Comment by jdalsem** [comment]
Ok i will see if these changes can go in

**Pull request closed without merging**
